!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  armor_big_armor_ratio: 3.0
  armor_max_aspect_ratio: 4.8
  armor_min_aspect_ratio: 0.5
  armor_small_armor_ratio: 1.5
  blue_hue_max: 130
  blue_hue_min: 100
  blue_sat_max: 255
  blue_sat_min: 100
  blue_val_max: 255
  blue_val_min: 50
  brightness_thresh: 150
  digit_big: 250
  digit_small: 28
  digit_threshold: 0.75
  draw_color_e_l_center: 4
  draw_color_e_light: 7
  draw_color_e_r_center: 3
  draw_color_e_rect: 5
  draw_e_l_center: true
  draw_e_label: true
  draw_e_light: true
  draw_e_r_center: true
  draw_e_rect: true
  enemy_color: 0
  enemy_type: 0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      armor_big_armor_ratio: 3.0
      armor_max_aspect_ratio: 4.8
      armor_min_aspect_ratio: 0.5
      armor_small_armor_ratio: 1.5
      blue_hue_max: 130
      blue_hue_min: 100
      blue_sat_max: 255
      blue_sat_min: 100
      blue_val_max: 255
      blue_val_min: 50
      brightness_thresh: 150
      digit_big: 250
      digit_small: 28
      digit_threshold: 0.75
      draw_color_e_l_center: 4
      draw_color_e_light: 7
      draw_color_e_r_center: 3
      draw_color_e_rect: 5
      draw_e_l_center: true
      draw_e_label: true
      draw_e_light: true
      draw_e_r_center: true
      draw_e_rect: true
      draw_e_points: true
      enemy_color: 0
      enemy_type: 0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      light_max_angle_diff: 15.0
      light_max_height_diff_ratio: 0.5
      light_max_ratio: 0.6
      light_max_y_diff_ratio: 0.3
      light_min_area: 50.0
      light_min_height: 14.0
      light_min_solidity: 0.7
      light_min_x_diff_ratio: 0.5
      morph_close_size: 5
      morph_kernel_size: 4
      morph_open_size: 3
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      red_hue_max: 10
      red_hue_min: 0
      red_sat_max: 255
      red_sat_min: 100
      red_val_max: 255
      red_val_min: 50
      state: true
      type: ''
    state: []
  light_max_angle_diff: 15.0
  light_max_height_diff_ratio: 0.5
  light_max_ratio: 0.6
  light_max_y_diff_ratio: 0.3
  light_min_area: 50.0
  light_min_height: 14.0
  light_min_solidity: 0.7
  light_min_x_diff_ratio: 0.5
  morph_close_size: 5
  morph_kernel_size: 4
  morph_open_size: 3
  red_hue_max: 10
  red_hue_min: 0
  red_sat_max: 255
  red_sat_min: 100
  red_val_max: 255
  red_val_min: 50
state: []
